[package]
name = "MedChainID"
version = "1.0.0"
authors = []

[addresses]
# Deployed contract address (v2 with patient_address support)
medchain = "0x73e3d9850a0a7c4ddf06b770d779cc0654854575399830128364973c5e3d3e9e" 

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"