[package]
name = "MedChainID"
version = "1.0.0"
authors = []

[addresses]
# Deployed contract address
medchain = "0xfdb11b3940120057998fc39463745d3e3d0342449fe85f324ef7a512c5ac9004" 

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"